version: "3"
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    restart: always

  app:
    container_name: dockerized_tests
    build:
      context: .
    volumes:
      - ./:/tests
    depends_on:
      - selenium
    command: "python script.py"