version: '3'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium