version: '3'

services:
  selenium:
    container_name: selenium_ct_tests
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tests
    depends_on:
      - selenium